server:
    port: 8005
spring:
    cloud:
        config:
            server:
                git:
                    default-label: master
                    uri: https://github.com/mcorverasoft/config-server-data.git
#                    username: ${GIT_USER}
#                    password: ${GIT_TOKEN}
                    username: mcorverasoft
                    password: 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
                    force-pull: true
                    clone-on-start: true
                    search-paths: data

application:
    name: config-service
